### ISSUE TITLE
Not clickable error 

### ISSUE THREAD

**Issue by jasonjackson** [Vacun/Vacun.github.io#1]
Was taking a look at this, but I'm getting the below error.  I'm wondering if you also get this?

Thanks!

`Scraping the listing number 28 on page 1, the count is 1
latitude = 40633593, longitude = -74090275
Traceback (most recent call last):
  File "zillow.py", line 142, in <module>
    driver.find_element_by_xpath('//div[@id="search-pagination-wrapper"]//li[@class="zsg-pagination-next"]').click()
  File "/Users/jasonkjackson/anaconda2/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/jasonkjackson/anaconda2/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/Users/jasonkjackson/anaconda2/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "/Users/jasonkjackson/anaconda2/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <li class="zsg-pagination-next">...</li> is not clickable at point (901, 577). Other element would receive the click: <div class="info flat-star-ratings sig-col">...</div>
  (Session info: chrome=58.0.3029.81)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.4 x86_64)`

**Comment by Vacun** [comment]
Hello Jason
I realized that there are 2 files named zillow.py
I removed the redundent one and ran the one that worked fine for me. It is in the folder called "Selenium/zillow with Selenium/

please run the zillow.py and see if it gives you the same error. it ran fine for me.
If it continues to give the same error, please let me know, and i will take a closer look at it.
P.S.
1. I remember that sometimes, the internet connection speed would effect the process.
